name: example-docker
on:
  workflow_call:

jobs:
  docker-browsers:
    runs-on: ubuntu-22.04
    strategy:
      fail-fast: false
      matrix:
        browser: [chrome, edge, electron, firefox]
    # from https://hub.docker.com/r/cypress/browsers/tags
    container:
      image: cypress/browsers:node-20.5.0-chrome-114.0.5735.133-1-ff-114.0.2-edge-114.0.1823.51-1
      options: --user 1001
    steps:
      - uses: actions/checkout@v6
        with:
          working-directory: cypress/e2e
          browser: ${{ matrix.browser }}