name: Run Cypress

on:
  workflow_dispatch:
    inputs:
      spec:
        description: "Test specification:"
        type: string
        default: 'cypress/e2e/**/*cy.js'
        required: true

jobs:
  cypress-run:
    runs-on: ubuntu-22.04
    container:
      image: cypress/browsers:node-20.11.0-chrome-121.0.6167.184-1-ff-123.0-edge-121.0.2277.128-1
    steps:
      - name: set dynamic variables
        id: name
        run: |
          echo "::set-output name=spec::${SPEC:-"cypress/e2e/**/*.cy.js"}"

      - name: Checkout
        uses: actions/checkout@v2

      - run: npm install

      - name: Cypress run
        uses: cypress-io/github-action@v6
        with:
          browser: chrome
          config-file: cypress.config.js
          spec: ${{ steps.name.outputs.spec }}

      - name: Upload screenshots on failure
        uses: actions/upload-artifact@v4.3.1
        if: failure()
        with:
          name: cypress-screenshots
          path: cypress/screenshots

      - name: Upload videos on failure
        uses: actions/upload-artifact@v4.3.1
        if: failure()
        with:
          name: cypress-videos
          path: cypress/videos